title: My Blogs
subtitle: Blogs about my internship and personal projects 
field: >-  # this means to ignore newlines until "baseurl:"
           AI and ML explorer

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About me 
      url: /about
    - text: Blogs
      url: /blog

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: Suman.jpg
author: Nay Oo Lwin
author_bio: Robotics enthusiast in autonomous field. Exploring navigation algorithms, deep learning with computer vision, experimenting ML models and open source developer at JdeRobot
author_email: "suman.nay17half1999@gmail.com"
author_location: India
typewrite-text: Here, my blogs are about my internships and personal projects 
# typewrite-text: Here, my blogs are about my internships and personal projects

# Experiences
author_work_experiences:
            - company_name: JdeRobot organization
              company_logo: logo.jpg
              company_url: http://jderobot.github.io/RoboticsAcademy/
              designation: Software Engineer Intern
              description: Open source collaboration on ROS and Gazebo
              visibility: true

# Education
author_education_details:
              - college_logo: JNTU.jpg
                college_name: Jawaharlal Nehru Technological University Hyderabad (JNTUH)
                college_url: https://www.jntuhceh.ac.in/
                college_degree: B.Tech Mechanical Engineering 
                description: Bachelor of Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: ROS.png
                project_title: ROS and Gazebo on web template
                project_description: Worked on integration of Gazebo(gzclient) and ROS on web application with docker
                project_url: https://github.com/JdeRobot/RoboticsAcademy/pull/772
                visibility: true
          

# social links
github_username:  NayOoLwin5
facebook_username: nayoo.lwin.750
linkedin_username: nay-oo-lwin-4b3976199
Youtube_channel : UCAHyRo_zoWFP2gSzBGJWyIw

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 4305

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
